// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Text struct {
	ID        int32
	Data      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Voice struct {
	ID        string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
