// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: jeka.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRandomTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRandomTextRequest) Reset() {
	*x = GetRandomTextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jeka_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandomTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomTextRequest) ProtoMessage() {}

func (x *GetRandomTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jeka_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomTextRequest.ProtoReflect.Descriptor instead.
func (*GetRandomTextRequest) Descriptor() ([]byte, []int) {
	return file_jeka_proto_rawDescGZIP(), []int{0}
}

type CreateRandomTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateRandomTextRequest) Reset() {
	*x = CreateRandomTextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jeka_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRandomTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRandomTextRequest) ProtoMessage() {}

func (x *CreateRandomTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jeka_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRandomTextRequest.ProtoReflect.Descriptor instead.
func (*CreateRandomTextRequest) Descriptor() ([]byte, []int) {
	return file_jeka_proto_rawDescGZIP(), []int{1}
}

type GetRandomTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *GetRandomTextResponse) Reset() {
	*x = GetRandomTextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jeka_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandomTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomTextResponse) ProtoMessage() {}

func (x *GetRandomTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jeka_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomTextResponse.ProtoReflect.Descriptor instead.
func (*GetRandomTextResponse) Descriptor() ([]byte, []int) {
	return file_jeka_proto_rawDescGZIP(), []int{2}
}

func (x *GetRandomTextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CreateRandomTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateRandomTextResponse) Reset() {
	*x = CreateRandomTextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jeka_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRandomTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRandomTextResponse) ProtoMessage() {}

func (x *CreateRandomTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jeka_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRandomTextResponse.ProtoReflect.Descriptor instead.
func (*CreateRandomTextResponse) Descriptor() ([]byte, []int) {
	return file_jeka_proto_rawDescGZIP(), []int{3}
}

type GetRandomVideoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRandomVideoRequest) Reset() {
	*x = GetRandomVideoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jeka_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandomVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomVideoRequest) ProtoMessage() {}

func (x *GetRandomVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jeka_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomVideoRequest.ProtoReflect.Descriptor instead.
func (*GetRandomVideoRequest) Descriptor() ([]byte, []int) {
	return file_jeka_proto_rawDescGZIP(), []int{4}
}

type GetRandomVideoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetRandomVideoResponse) Reset() {
	*x = GetRandomVideoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jeka_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandomVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomVideoResponse) ProtoMessage() {}

func (x *GetRandomVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jeka_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomVideoResponse.ProtoReflect.Descriptor instead.
func (*GetRandomVideoResponse) Descriptor() ([]byte, []int) {
	return file_jeka_proto_rawDescGZIP(), []int{5}
}

func (x *GetRandomVideoResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetRandomImgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *GetRandomImgRequest) Reset() {
	*x = GetRandomImgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jeka_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandomImgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomImgRequest) ProtoMessage() {}

func (x *GetRandomImgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jeka_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomImgRequest.ProtoReflect.Descriptor instead.
func (*GetRandomImgRequest) Descriptor() ([]byte, []int) {
	return file_jeka_proto_rawDescGZIP(), []int{6}
}

func (x *GetRandomImgRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GetRandomImgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetRandomImgResponse) Reset() {
	*x = GetRandomImgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jeka_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandomImgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomImgResponse) ProtoMessage() {}

func (x *GetRandomImgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jeka_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomImgResponse.ProtoReflect.Descriptor instead.
func (*GetRandomImgResponse) Descriptor() ([]byte, []int) {
	return file_jeka_proto_rawDescGZIP(), []int{7}
}

func (x *GetRandomImgResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_jeka_proto protoreflect.FileDescriptor

var file_jeka_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6a, 0x65, 0x6b, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x16, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61,
	0x6e, 0x64, 0x6f, 0x6d, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x2b, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x54, 0x65, 0x78, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x1a, 0x0a, 0x18,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x54, 0x65, 0x78, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x52,
	0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x2a, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x2b, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x28, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x32, 0x8f, 0x02, 0x0a, 0x04, 0x4a, 0x65, 0x6b, 0x61, 0x12, 0x3e, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x54, 0x65, 0x78, 0x74, 0x12, 0x15,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a,
	0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x54, 0x65, 0x78,
	0x74, 0x12, 0x18, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x49, 0x6d, 0x67, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x69, 0x6d, 0x73, 0x6f, 0x66, 0x74, 0x65, 0x6e, 0x67, 0x2f,
	0x6a, 0x65, 0x6b, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_jeka_proto_rawDescOnce sync.Once
	file_jeka_proto_rawDescData = file_jeka_proto_rawDesc
)

func file_jeka_proto_rawDescGZIP() []byte {
	file_jeka_proto_rawDescOnce.Do(func() {
		file_jeka_proto_rawDescData = protoimpl.X.CompressGZIP(file_jeka_proto_rawDescData)
	})
	return file_jeka_proto_rawDescData
}

var file_jeka_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_jeka_proto_goTypes = []any{
	(*GetRandomTextRequest)(nil),     // 0: GetRandomTextRequest
	(*CreateRandomTextRequest)(nil),  // 1: CreateRandomTextRequest
	(*GetRandomTextResponse)(nil),    // 2: GetRandomTextResponse
	(*CreateRandomTextResponse)(nil), // 3: CreateRandomTextResponse
	(*GetRandomVideoRequest)(nil),    // 4: GetRandomVideoRequest
	(*GetRandomVideoResponse)(nil),   // 5: GetRandomVideoResponse
	(*GetRandomImgRequest)(nil),      // 6: GetRandomImgRequest
	(*GetRandomImgResponse)(nil),     // 7: GetRandomImgResponse
}
var file_jeka_proto_depIdxs = []int32{
	0, // 0: Jeka.GetRandomText:input_type -> GetRandomTextRequest
	1, // 1: Jeka.CreateRandomText:input_type -> CreateRandomTextRequest
	6, // 2: Jeka.GetRandomImg:input_type -> GetRandomImgRequest
	4, // 3: Jeka.GetRandomVideo:input_type -> GetRandomVideoRequest
	2, // 4: Jeka.GetRandomText:output_type -> GetRandomTextResponse
	3, // 5: Jeka.CreateRandomText:output_type -> CreateRandomTextResponse
	7, // 6: Jeka.GetRandomImg:output_type -> GetRandomImgResponse
	5, // 7: Jeka.GetRandomVideo:output_type -> GetRandomVideoResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jeka_proto_init() }
func file_jeka_proto_init() {
	if File_jeka_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jeka_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetRandomTextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jeka_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateRandomTextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jeka_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetRandomTextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jeka_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateRandomTextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jeka_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetRandomVideoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jeka_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetRandomVideoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jeka_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetRandomImgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jeka_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetRandomImgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jeka_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jeka_proto_goTypes,
		DependencyIndexes: file_jeka_proto_depIdxs,
		MessageInfos:      file_jeka_proto_msgTypes,
	}.Build()
	File_jeka_proto = out.File
	file_jeka_proto_rawDesc = nil
	file_jeka_proto_goTypes = nil
	file_jeka_proto_depIdxs = nil
}
